# Server configuration
server.port=8084
# MongoDB configuration (Use environment variables for security)
spring.data.mongodb.uri=mongodb+srv://ranimabbessi:Y3whR02H5skyatm2@cluster0.mtilp.mongodb.net/legy?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.uri=mongodb://legy:legy123@mongo:27017/leggydb?authSource=admin
# Mail configuration (Use environment variables)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=legy.services@gmail.com
spring.mail.password=pkcp jtpa lajd fsvy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jackson.time-zone=UTC
spring.data.mongodb.time-zone=UTC
# Logging configuration
logging.level.org.apache.kafka.clients.NetworkClient=ERROR
# Logging configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.payment.infrastructure.audit=INFO
spring.data.mongodb.auto-index-creation=true

# IMAP settings for fetching emails
spring.mail.imap.host=imap.gmail.com
spring.mail.imap.port=993
spring.mail.imap.username=legy.services@gmail.com
spring.mail.imap.password=pkcp jtpa lajd fsvy
spring.mail.properties.mail.imap.ssl.enable=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


firebase.server-key=AIzaSyAa7hKNd3kD-8m99ZMz2dR3k5mkJoD3VPo
weather.api.key=a987989315b6af700875f3b5cbe32cf7
#Google maps API key
google.maps.api.key=AIzaSyCX28rwkL8_jds7KQDL9iV6V_z21f-FKRA
# SpringDoc configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
logging.level.org.springdoc=DEBUG
# Redis host and port
spring.data.redis.host=redis
spring.data.redis.port=6379
# (Optional) Connection timeout in milliseconds
spring.data.redis.timeout=2000
# (Optional) Use standalone mode (this is default)
spring.data.redis.client-type=lettuce
# Stripe API Key (Use environment variable)
stripe.secret.key=sk_test_51QmXBBHpqOAXxBrdbHY6xbnGYewgtg87j8skSAwKL0RXlUgOrl6dxGN6SRsdT6h1DnFTzlMb1qbuw3kmDWoSBXTD00R1rzMRKH
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# ==== Google OAuth2 Login ====
spring.security.oauth2.client.registration.google.client-id=347229550581-mglvj3kis7pnkc54acv9r2nh10scjn5d.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.client-name=Google
# Optional (can help with token exchange stability)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.registration.facebook.client-id=686431460720084
spring.security.oauth2.client.registration.facebook.client-secret=9b8de62c71aab6b091408af2f9bf8cf7
spring.security.oauth2.client.registration.facebook.scope=public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.facebook.client-name=Facebook
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v11.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v11.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,first_name,last_name
spring.security.oauth2.client.provider.facebook.user-name-attribute=id
spring.main.allow-bean-definition-overriding=true
twilio.account.sid=ACd6589d585ef00db061920fb52726c13f
twilio.auth.token=4802df5b42eb4240119ae7b291fe5c9b
twilio.whatsapp.from=whatsapp:+14155238886
frontend-url=https://dev.moderator.legy.bramasquare.com
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
aws.region=eu-north-1
aws.s3.bucket=legy-application-bucket
aws.access-key=AKIAR4XH7R33BPVYGUKY
aws.secret-key=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

management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
recommendation.api.url=http://localhost:8000
logging.level.recommendation.infrastructure.persistence=DEBUG
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true