FROM jenkins/jenkins:lts

USER root

# Install latest Docker CLI and Compose plugin
RUN apt-get update && \
    apt-get install -y curl ca-certificates && \
    curl -fsSL https://get.docker.com | sh && \
    mkdir -p /usr/local/lib/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.28.2/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose && \
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
