global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'  # Default metrics path if using Prometheus plugin in Jenkins
    static_configs:
      - targets: [ '192.168.56.108:9090' ]

  - job_name: 'spring-boot-app'
    metrics_path: '/legy/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.56.108:8084' ]
  

  - job_name: 'jenkins'
    metrics_path: '/prometheus'  # Default metrics path if using Prometheus plugin in Jenkins
    static_configs:
      - targets: ['192.168.56.108:8080']