apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: legy-local

resources:
  - namespace.yaml
  - zookeeper-deployment.yaml
  - kafka-deployment.yaml
  - mongo-deployment.yaml
  - redis-deployment.yaml
  - leggy-deployment.yaml
  - services.yaml
