apiVersion: v1
kind: Secret
metadata:
  name: leggy-secrets
  namespace: legy-local
type: Opaque
stringData:
  MONGO_URI: "mongodb://legy:legy123@mongo:27017/leggydb?authSource=admin"
  NEXUS_USERNAME: "admin"
  NEXUS_PASSWORD: "legyPFE2025"
  NEXUS_URL: "http://nexus:8081"
