package ordering.infrastructure.Document;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

@Document("moderatorTokens")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ModeratorTokenDocument {
    @Id
    private String id; // Optional, auto-generated by MongoDB

    @Indexed(unique = true) // Ensure one token per moderator
    private String moderatorId;

    private String fcmToken;

    private Instant createdAt; // Track when the token was registered
}