# k8s-local/monitoring/leggy-servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: leggy-servicemonitor
  namespace: monitoring
  labels:
    team: leggy
spec:
  selector:
    matchLabels:
      app: leggy       # doit correspondre au label “app: leggy” de votre Service leggy-service
  namespaceSelector:
    matchNames:
      - legy-local     # namespace où tourne l’application leggy
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
